services:
  - type: web
    name: snacklirio-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snacklirio-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://snacklirio.vercel.app

databases:
  - name: snacklirio-db
    databaseName: snacklirio
    plan: free
    region: frankfurt
